name: Build Kivy Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-22.04  # Use Ubuntu 22.04 instead of latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install required system packages
      run: |
        sudo apt update
        sudo apt install -y libtinfo5 libncurses5 wget unzip
    
    - name: Setup Android SDK and NDK cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer/android/platform/android-sdk
          ~/.buildozer/android/platform/android-ndk-r25c
        key: android-sdk-ndk-${{ runner.os }}-v3
        restore-keys: |
          android-sdk-ndk-${{ runner.os }}-
    
    - name: Pre-download Android NDK (if not cached)
      run: |
        NDK_DIR="$HOME/.buildozer/android/platform"
        NDK_ZIP="android-ndk-r25c-linux.zip"
        NDK_URL="https://dl.google.com/android/repository/${NDK_ZIP}"
        NDK_FOLDER="android-ndk-r25c"
        
        mkdir -p "$NDK_DIR"
        cd "$NDK_DIR"
        
        if [ ! -d "$NDK_FOLDER" ]; then
          echo "Downloading Android NDK..."
          # Use wget with retry and resume capabilities
          wget --continue --tries=3 --timeout=30 "${NDK_URL}" -O "${NDK_ZIP}"
          
          if [ -f "${NDK_ZIP}" ]; then
            echo "Extracting NDK..."
            unzip -q "${NDK_ZIP}"
            rm "${NDK_ZIP}"
            echo "NDK installation complete"
          else
            echo "Failed to download NDK"
            exit 1
          fi
        else
          echo "NDK already exists, skipping download"
        fi
    
    - name: Build with Buildozer
      uses: digreatbrian/buildozer-action@main
      with:
        python-version: '3.8'
        work-dir: '.'
        buildozer-cmd: 'buildozer android debug'
      env:
        PYTHONUNBUFFERED: 1
        ANDROID_SDK_ROOT: /home/runner/android-sdk
        ANDROID_HOME: /home/runner/android-sdk
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
      if: always()
    
    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/python-for-android/dist/dists/*/build.log
          .buildozer/android/platform/python-for-android/dist/dists/*/build.log.*
          .buildozer/android/app/build/outputs/logs/
      if: failure()
