name: Build Kivy Android APK
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build with Buildozer
      uses: digreatbrian/buildozer-action@main
      with:
        # Command to run (buildozer android debug is the default)
        command: buildozer android debug
        # Path to buildozer.spec file (optional, defaults to ./buildozer.spec)
        buildozer_spec_path: ./buildozer.spec
        # Repository token for private dependencies (optional)
        repository_token: ${{ secrets.GITHUB_TOKEN }}
        # Additional environment variables (optional)
        buildozer_env: |
          PYTHONUNBUFFERED=1
          ANDROID_SDK_ROOT=/home/runner/android-sdk
          ANDROID_HOME=/home/runner/android-sdk
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
      if: always()
    
    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/python-for-android/dist/dists/*/build.log
          .buildozer/android/platform/python-for-android/dist/dists/*/build.log.*
          .buildozer/android/app/build/outputs/logs/
      if: failure()
