name: Build Kivy Android APK (Manual)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          libtinfo5 \
          libncurses5 \
          build-essential \
          git \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-dev \
          libssl-dev \
          libffi-dev \
          zlib1g-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          wget \
          curl \
          llvm \
          libncurses5-dev \
          libncursesw5-dev \
          xz-utils \
          tk-dev \
          libxml2-dev \
          libxmlsec1-dev \
          libffi-dev \
          liblzma-dev \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          cmake \
          libltdl-dev \
          ccache
    
    - name: Install Buildozer
      run: |
        pip install buildozer
        pip install cython
    
    - name: Build APK
      run: |
        buildozer android debug
      env:
        PYTHONUNBUFFERED: 1
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
      if: always()
    
    - name: Upload Build Logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/python-for-android/dist/dists/*/build.log
          .buildozer/android/platform/python-for-android/dist/dists/*/build.log.*
          .buildozer/android/app/build/outputs/logs/
      if: failure()
